update .github/workflows/custombuild.yml

diff --git a/.github/workflows/custombuild.yml b/.github/workflows/custombuild.yml
--- a/.github/workflows/custombuild.yml
+++ b/.github/workflows/custombuild.yml
@@ -239,8 +239,8 @@ jobs:
                     FILEURL="https://downloads.openwrt.org/releases/$LATEST/packages/x86_64/$S/$PKGFILE"
                     echo "[INFO] Paket ditemukan: $FILEURL"
                     # wget -q -O "tmp-ipk/$(basename "$PKGFILE")" "$FILEURL" \
-                      && FOUND=1 && break \
-                      || echo "[ERROR] Gagal download $PKGFILE, lanjut paket lain"
+                    #   && FOUND=1 && break \
+                    #   || echo "[ERROR] Gagal download $PKGFILE, lanjut paket lain"
                 fi
             fi
           done
